<div class="text-center">
    <ul class="pagination">

            <li class="disabled"><a href="#">« Předchozí</a></li>


                <li class="disabled"><a href="#">1</a></li>



                <li><a href="#" rel="next">2</a></li>



                <li><a href="#" rel="next">3</a></li>



                <li><a href="#" rel="next">4</a></li>



                <li><a href="#" rel="next">5</a></li>



            <li><a href="#" rel="next">Další »</a></li>

    </ul>
</div>
